### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by vkorbes** [kris-nova/T_T#4]
What do we put on this line of the license file?

`Copyright (c) [year] [fullname]`

**Comment by krisnova** [comment]
2016-2017 The T_T Authors

**Comment by vkorbes** [comment]
K!

**Comment by krisnova** [comment]
We will then need to offer a /AUTHORS file with everyone's name like this one:

https://github.com/django/django/blob/master/AUTHORS

**Comment by vkorbes** [comment]
There we go: https://github.com/kris-nova/T_T/blob/master/AUTHORS
